<<<<<<<< HEAD:Profile/migrations/0003_profile_image.py
# Generated by Django 5.0.2 on 2024-02-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
========
# Generated by Django 5.0.2 on 2024-03-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
>>>>>>>> profile:Profile/migrations/0002_profile_avatar.py
