# Generated by Django 5.0.2 on 2024-03-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='image',
        ),
    ]
